[package]
name = "poker_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_pixel = { path = "../../../rust-pixel", default-features = false, features = ["web"] }
poker_lib = { path = "../lib" }
texas_lib = { path = "../texas" }
gin_rummy_lib = { path = "../../gin_rummy/lib" }
wasm-bindgen = "0.2.92"
web-sys = "0.3.4"
wasm-logger = "0.2.0"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"


