[package]
name = "pixel_macro"
version = "0.2.0"
edition = "2021"
publish = true
description = "2d pixel art game engine macro tools"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
