language = "C"
no_includes = true

[parse]
parse_deps = true
exclude = [
    "sdl2",
    "crossterm",
    "log",
    "itertools",
    "log4rs",
    "bincode",
    "rand",
    "serde_json",
    "rust_pixel",
]

[export]
prefix = "rs_"

[enum]
rename_variants = "SnakeCase"
